/*
Created: 6/21/2021
Modified: 6/23/2021
Model: Microsoft SQL Server 2014
Database: MS SQL Server 2014
*/


-- Create tables section -------------------------------------------------

-- Table LOAISP

CREATE TABLE [LOAISP]
(
 [MALOAISP] Char(6) NOT NULL,
 [TENLOAISP] Nvarchar(30) NULL
)
go

-- Add keys for table LOAISP

ALTER TABLE [LOAISP] ADD CONSTRAINT [PK_LOAISP] PRIMARY KEY ([MALOAISP])
go

-- Table SANPHAM

CREATE TABLE [SANPHAM]
(
 [MASP] Char(6) NOT NULL,
 [TENSP] Nvarchar(30) NULL,
 [MAUSAC] Nvarchar(10) NULL,
 [DONGIA] Int NULL,
 [NGAYTHEM] Date NULL,
 [ANHBIA] Char(14) NULL,
 [TRANGTHAI] Bit NULL,
 [MALOAISP] Char(6) NULL,
 [MANV] Char(10) NULL
)
go

-- Create indexes for table SANPHAM

CREATE INDEX [IX_Relationship3] ON [SANPHAM] ([MALOAISP])
go

CREATE INDEX [IX_Relationship7] ON [SANPHAM] ([MANV])
go

-- Add keys for table SANPHAM

ALTER TABLE [SANPHAM] ADD CONSTRAINT [PK_SANPHAM] PRIMARY KEY ([MASP])
go

-- Table KHUYENMAI

CREATE TABLE [KHUYENMAI]
(
 [MAKM] Char(3) NOT NULL,
 [HINHTHUC] Nvarchar(20) NULL,
 [GIATRI] Int NULL,
 [BATDAU] Datetime NULL,
 [KETTHUC] Datetime NULL,
 [MANV] Char(10) NULL
)
go

-- Create indexes for table KHUYENMAI

CREATE INDEX [IX_Relationship9] ON [KHUYENMAI] ([MANV])
go

-- Add keys for table KHUYENMAI

ALTER TABLE [KHUYENMAI] ADD CONSTRAINT [PK_KHUYENMAI] PRIMARY KEY ([MAKM])
go

-- Table KHACHHANG

CREATE TABLE [KHACHHANG]
(
 [SDT] Varchar(15) NOT NULL,
 [HOTENKH] Nvarchar(30) NULL,
 [NTNS] Datetime NULL,
 [EMAIL] Nchar(50) NULL
)
go

-- Add keys for table KHACHHANG

ALTER TABLE [KHACHHANG] ADD CONSTRAINT [PK_KHACHHANG] PRIMARY KEY ([SDT])
go

-- Table HINHSP

CREATE TABLE [HINHSP]
(
 [MAHA] Char(14) NOT NULL,
 [MASP] Char(6) NOT NULL
)
go

-- Add keys for table HINHSP

ALTER TABLE [HINHSP] ADD CONSTRAINT [PK_HINHSP] PRIMARY KEY ([MAHA],[MASP])
go

-- Table TKKH

CREATE TABLE [TKKH]
(
 [ID] Varchar(15) NOT NULL,
 [PASS] Char(15) NULL
)
go

-- Add keys for table TKKH

ALTER TABLE [TKKH] ADD CONSTRAINT [PK_TKKH] PRIMARY KEY ([ID])
go

-- Table NHANVIEN

CREATE TABLE [NHANVIEN]
(
 [MANV] Char(10) NOT NULL,
 [HOTENNV] Nvarchar(30) NULL,
 [NTNS] Datetime NULL,
 [CHUCVU] Nvarchar(30) NULL,
 [EMAIL] Nchar(50) NULL,
 [SDT] Varchar(15) NULL
)
go

-- Add keys for table NHANVIEN

ALTER TABLE [NHANVIEN] ADD CONSTRAINT [PK_NHANVIEN] PRIMARY KEY ([MANV])
go

-- Table TKNV

CREATE TABLE [TKNV]
(
 [MANV] Char(10) NOT NULL,
 [PASS] Char(15) NULL
)
go

-- Add keys for table TKNV

ALTER TABLE [TKNV] ADD CONSTRAINT [PK_TKNV] PRIMARY KEY ([MANV])
go

-- Table DONHANG

CREATE TABLE [DONHANG]
(
 [MADH] Char(10) NOT NULL,
 [NGAYDH] Datetime NULL,
 [SDT] Varchar(15) NULL,
 [MANV] Char(10) NULL
)
go

-- Create indexes for table DONHANG

CREATE INDEX [IX_Relationship13] ON [DONHANG] ([SDT])
go

CREATE INDEX [IX_Relationship15] ON [DONHANG] ([MANV])
go

-- Add keys for table DONHANG

ALTER TABLE [DONHANG] ADD CONSTRAINT [PK_DONHANG] PRIMARY KEY ([MADH])
go

-- Table CTDH

CREATE TABLE [CTDH]
(
 [MASP] Char(6) NOT NULL,
 [MADH] Char(10) NOT NULL,
 [SLMUA] Int NULL,
 [GIABAN] Int NULL,
 [TONGTIEN] Int NULL,
 [MAKM] Char(3) NULL
)
go

-- Create indexes for table CTDH

CREATE INDEX [IX_Relationship14] ON [CTDH] ([MAKM])
go

-- Add keys for table CTDH

ALTER TABLE [CTDH] ADD CONSTRAINT [PK_CTDH] PRIMARY KEY ([MASP],[MADH])
go

-- Table SIZE

CREATE TABLE [SIZE]
(
 [MASP] Char(6) NOT NULL,
 [KIEUSZIE] Nchar(3) NOT NULL,
 [SOLUONG] Int NULL
)
go

-- Add keys for table SIZE

ALTER TABLE [SIZE] ADD CONSTRAINT [PK_SIZE] PRIMARY KEY ([MASP],[KIEUSZIE])
go

-- Create foreign keys (relationships) section ------------------------------------------------- 


ALTER TABLE [HINHSP] ADD CONSTRAINT [Relationship2] FOREIGN KEY ([MASP]) REFERENCES [SANPHAM] ([MASP]) ON UPDATE NO ACTION ON DELETE NO ACTION
go



ALTER TABLE [SANPHAM] ADD CONSTRAINT [Relationship3] FOREIGN KEY ([MALOAISP]) REFERENCES [LOAISP] ([MALOAISP]) ON UPDATE NO ACTION ON DELETE NO ACTION
go



ALTER TABLE [TKKH] ADD CONSTRAINT [Relationship5] FOREIGN KEY ([ID]) REFERENCES [KHACHHANG] ([SDT]) ON UPDATE NO ACTION ON DELETE NO ACTION
go



ALTER TABLE [SANPHAM] ADD CONSTRAINT [Relationship7] FOREIGN KEY ([MANV]) REFERENCES [NHANVIEN] ([MANV]) ON UPDATE NO ACTION ON DELETE NO ACTION
go



ALTER TABLE [KHUYENMAI] ADD CONSTRAINT [Relationship9] FOREIGN KEY ([MANV]) REFERENCES [NHANVIEN] ([MANV]) ON UPDATE NO ACTION ON DELETE NO ACTION
go



ALTER TABLE [TKNV] ADD CONSTRAINT [Relationship10] FOREIGN KEY ([MANV]) REFERENCES [NHANVIEN] ([MANV]) ON UPDATE NO ACTION ON DELETE NO ACTION
go



ALTER TABLE [CTDH] ADD CONSTRAINT [Relationship11] FOREIGN KEY ([MASP]) REFERENCES [SANPHAM] ([MASP]) ON UPDATE NO ACTION ON DELETE NO ACTION
go



ALTER TABLE [CTDH] ADD CONSTRAINT [Relationship12] FOREIGN KEY ([MADH]) REFERENCES [DONHANG] ([MADH]) ON UPDATE NO ACTION ON DELETE NO ACTION
go



ALTER TABLE [DONHANG] ADD CONSTRAINT [Relationship13] FOREIGN KEY ([SDT]) REFERENCES [KHACHHANG] ([SDT]) ON UPDATE NO ACTION ON DELETE NO ACTION
go



ALTER TABLE [CTDH] ADD CONSTRAINT [Relationship14] FOREIGN KEY ([MAKM]) REFERENCES [KHUYENMAI] ([MAKM]) ON UPDATE NO ACTION ON DELETE NO ACTION
go



ALTER TABLE [DONHANG] ADD CONSTRAINT [Relationship15] FOREIGN KEY ([MANV]) REFERENCES [NHANVIEN] ([MANV]) ON UPDATE NO ACTION ON DELETE NO ACTION
go



ALTER TABLE [SIZE] ADD CONSTRAINT [Relationship16] FOREIGN KEY ([MASP]) REFERENCES [SANPHAM] ([MASP]) ON UPDATE NO ACTION ON DELETE NO ACTION
go




